name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.4,name=iPhone X']

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Start xcodebuild test
        run: xcodebuild clean test -project githubtest.xcodeproj -scheme githubtest -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
           destination: ${{ matrix.destination }}
